Cargo.lock, Cargo.toml, atoma-proxy/src/server/config.rs, atoma-state/src/config.rs, config.example.toml
The config of `atoma_service` and `atoma_state` can now be overwritten with env var.
E.g. `ATOMA_STATE__DATABASE_URL` will overwrite
```
[atoma_state]
database_url=""
```
`ATOMA_SERVICE__HF_TOKEN` will overwrite
```
[atoma_service]
hf_token = ""
```
=> feat: add the ability to override config with env var

atoma-proxy/src/server/chat_completions.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
When no stacks are found for the given model. We find the best task with the node with the best price and allocate maximum number of tokens that the node allows us.
=> feat: allocate stack with best price

atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/http_server.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Check the signature when calling update public address for a node.
- check if the signature is valid
- check if the signature is for the same small id that's in the request
=> feat: check the signature on updating public address of the node

Cargo.lock, Cargo.toml, atoma-auth/Cargo.toml, atoma-auth/src/auth.rs, atoma-auth/src/config.rs, atoma-auth/src/lib.rs, atoma-proxy/Cargo.toml, atoma-proxy/src/main.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs, config.example.toml
Add atoma-auth module, this modules takes care of the jwt and api token validation.
The api token can be generated only when a valid jwt access token is provided.
Valid jwt access tokens holds the hash of the refresh token that was used to generate it. If the refresh token is not in the DB (was revoked) all the corresponding access tokens are revoked as well.
=> feat: auth module, for jwt and api tokens

Cargo.lock, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/mod.rs, atoma-proxy-service/src/handlers/stats.rs, atoma-proxy-service/src/lib.rs, atoma-proxy-service/src/proxy_service.rs, atoma-proxy-service/src/query.rs, atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/middleware.rs, atoma-proxy/src/server/streamer.rs, atoma-state/Cargo.toml, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add stats for the dashboard,
- hourly based latency
- hourly based compute units processed
Add daemons endpoints and tables for both of them. They are updated whenever we update the nodes performances tables.
=> feat: add stats for the dashboard

atoma-proxy/src/server/middleware.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Validate the api token on inference request (check if it's in the DB, all revoked tokens are deleted).
=> feat: validate api token on inference request

atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/stats.rs, atoma-proxy/src/server/http_server.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20241213104339_create_initial_schema.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Review #60 first, and after merge this can be reviewed.
Add country column to nodes. So we can have a distribution in the dashboard.
=> feat: add country to nodes

atoma-state/src/state_manager.rs
=> fix: typo in table name

README.md, atoma-proxy/src/server/middleware.rs
Just remove the missed static proxy password references.
=> chore: cleanup the leftovers after static password removal

Cargo.lock, atoma-proxy-service/Cargo.toml, atoma-proxy-service/src/handlers/stacks.rs, atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/handlers/embeddings.rs, atoma-state/src/state_manager.rs
Return stack timestamp alongside with the stack itself.
I don't want to add the timestamp to stack struct, because it would not reflect the event that's emitted.
=> feat: return stack timestamp

atoma-proxy-service/src/handlers/tasks.rs, atoma-proxy-service/src/lib.rs, atoma-proxy-service/src/proxy_service.rs, atoma-proxy/src/main.rs, atoma-proxy/src/server/config.rs, config.example.toml
Add model capabilities to proxy. This is for the example endpoint usage on the dashboard.
=> feat: hardcode model capabilities into proxy

atoma-auth/src/auth.rs, atoma-auth/src/sui/mod.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250108091311_remove_wallet_constrain.sql, atoma-state/src/migrations/20250108092319_add-usdc-digest-table.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
- Enable multiple users to have the same wallet.
- Get rid of the timestamp in the balance table.
- Introduce new table with the usdc digests. Each digest can be processed only once.
=> feat: digest table and multiple user with the same wallet

Cargo.lock, atoma-auth/Cargo.toml, atoma-auth/src/auth.rs, atoma-auth/src/lib.rs, atoma-proxy-service/src/handlers/auth.rs
This is for easier handling of the responses. E.g. user already registered now can throw 409 (conflict).
=> chore: change anyhow to custom error on auth

atoma-state/src/migrations/20250109151445_fix-usdc-balance-check.sql
The balance should be able to drop to zero. It was required to be non-zero.
=> fix: balance change can be zero

atoma-proxy/src/server/handlers/nodes.rs, atoma-proxy/src/server/middleware.rs
Change the stacks size to buy to 1 million compute units.
=> chore: change default stacks size to buy to 1M

atoma-proxy-service/src/handlers/auth.rs, atoma-proxy/docs/openapi.yml
Return 401 if the user doesn't exist or the passwords doesn't match.
=> feat: return proper login error

README.md, atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/components/openapi.rs, docker-compose.yaml
- Changed the Atoma cloud service URL in README from `atomacloud.com` to `cloud.atoma.network`.
- Updated the OpenAPI documentation to reflect the new API URL from `https://api.atomacloud.com` to `https://api.atoma.network`.
=> fix: update API URLs in README and OpenAPI documentation

atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/handlers/nodes.rs, atoma-proxy/src/server/http_server.rs
- Introduced a new endpoint for creating a node lock for confidential compute.
- Updated the OpenAPI documentation to reflect the new endpoint and request/response structures.
- Refactored existing code to replace the previous models retrieve endpoint with the new create lock functionality.
=> refactor: add nodes create lock endpoint

config.example.toml
Add `google_client_id` to `config.example.toml`
=> fix: add google_client_id to config.example.toml

.github/workflows/release.yml, Dockerfile, README.md, atoma-auth/Cargo.toml, atoma-auth/src/auth.rs, atoma-auth/src/config.rs, atoma-auth/src/lib.rs, atoma-proxy-service/Cargo.toml, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-proxy/Cargo.toml, config.example.toml, docker-compose.yaml
Add feature flag for google oauth
=> feat: add google oauth (zklogin) behind feature flag

docker-compose.yaml
Frontend could not connect to the backend, because they ended up on different network.
=> fix: missing network in docker for prover

.codecov.yml, .github/dependabot.yml, .github/workflows/audit.yml, .github/workflows/coverage.yml, .github/workflows/deny.yml, .github/workflows/e2e.yml, deny.toml
This is continue the work that was done in https://github.com/atoma-network/atoma-node
=> ci: add some of the ci checks done on node

Cargo.lock, atoma-proxy/Cargo.toml, atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/handlers/models.rs, atoma-proxy/src/server/http_server.rs
Add cors layer to proxy, so it can be fetched from frontends.
Remove requirements for bearer token from `/v1/models` endpoint.
=> feat: add cors layer to proxy

docker-compose.dev.yaml
These volumes are not necessary for a dev environment since it's short lived.
=> build: remove unnecessary docker volumes

Dockerfile
Similar fixes to https://github.com/atoma-network/atoma-node/pull/431 which were required in order to build the failing [docker image build](https://github.com/atoma-network/atoma-proxy/actions/runs/13437149673)
=> build: update `Dockerfile` to use ubuntu for builds

atoma-auth/src/auth.rs, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/handlers/auth.rs, atoma-state/build.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250304082533_api_token_name.sql, atoma-state/src/migrations/20250304134031_fix-timestamps.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
- Add name to api tokens.
- change the create from get to post, add name to the request
- change the request from revoking from api token to id of the token
- Make the timestamp types the same for users and nodes.
=> feat: add name to api token

atoma-state/src/state_manager.rs
Before the non existing user was handled in the frontend, let just return 0 for non-existing user here to simplify the frontend.
Non-existing user means the user had not yet topped up his account. But the users exists because this function is behind auth.
=> feat: return 0 balance when user is not found

atoma-state/src/migrations/20250317104814_api_token_last_used_timestamp.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Whenever the api tokens is checked for validity, we count it as used and modify the timestamp.
=> feat: add last used timestamp for tokens

atoma-proxy-service/src/components/grafana.rs, atoma-proxy-service/src/handlers/stats.rs
Add interval to grafana query, the interval needs to be set on dashboard to return the proper interval, it's not part of the query itself (that's how grafana do it).
=> feat: add interval to grafana query

atoma-proxy-service/src/components/grafana.rs, atoma-proxy-service/src/handlers/stats.rs
Export the whole field config, which holds the cosmetic settings for the chart (e.g. fill opacity under line etc.)
=> feat: export whole field config from grafana

atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/metrics.rs, atoma-proxy/src/server/streamer.rs
We had metric for estimated tokens which feels kind of useless, because that's just the input size + max output length of model. I changed it to capture the total tokens from the inference results.
=> feat: change the estimated metrics to the real value

.env.example, Dockerfile, README.md, docker-compose.dev.yaml, docker-compose.yaml
Docker builds can now be deployed using the `ATOMA_LOG_LEVELS` env var, I highly recommend setting this at runtime to avoid confusion.
e.g.
```bash
ATOMA_LOG_LEVELS=trace docker compose --profile local up -d
```
will set the overall log level to `trace`
=> chore: use env variable to set logging levels

atoma-auth/src/auth.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
During oauth with try to insert into the `users` table, but the `password_salt` is `not null` so the query failed. In this PR we generate the `password_salt` for oauth users. When the user is already present the new password salt is ignored.
=> fix: oauth missing password_salt

atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-state/src/migrations/20250325062641_drop-users-name.sql, atoma-state/src/state_manager.rs, atoma-state/src/tests.rs, atoma-state/src/types.rs
Drop the `name` from `users` table. Since there is no user settings that can be changed drop some the save user profile function/endpoint as well.
=> feat: drop name from users table

atoma-proxy-service/docs/openapi.yml, atoma-proxy/src/server/middleware.rs
Acquire new stack in a tokio thread to prevent killing the code between acquiring and storing the stack (that can happen when the connection is dropped).
=> feat: acquire new stack in thread

Cargo.lock, Cargo.toml, atoma-proxy/Cargo.toml, atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/handlers/request_model.rs, atoma-proxy/src/server/http_server.rs, atoma-proxy/src/server/middleware.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
@Cifko we need to review this one very carefully, and test it throughly.
I have introduced a new struct `LockGuard` to ensure that the any acquire stack lock encapsules the entire logic of acquiring a new stack (and there are no possible race conditions between logical branches, otherwise).
This `LockGuard` also implements the `Drop` trait making sure that resources are cleanup appropriately. We should do the same for the `DashMap` use in the `atoma-node` for counting concurrent requests.
```rs
/// A guard that locks a stack for a user id.
///
/// This struct is used to lock a stack for a user id, so that no other concurrent requests can try to acquire a new stack,
/// to avoid buying multiple redundant stacks, at the same time (that is in a window of 300ms, following Sui's Mysticeti fast …
```
=> feat: add logic for acquire stack lock

atoma-proxy/src/server/handlers/models.rs
The auth was there twice. It should be only in the middleware
=> fix: remove auth from models handler

atoma-proxy/src/server/error.rs, atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/handlers/metrics.rs, atoma-proxy/src/server/middleware.rs
Due to overestimation of compute units, a node might not have enough available compute units for a stack and send a lock message to the proxy, in scenarios of multiple concurrent requests. This is not ideal, as the stack might not be locked (and actually far from it), so there is not reason for the proxy to locked it in its internal state.
Instead, we introduce a new status code `TOO_EARLY`, meaning that this request needs either to be retried at a moment's later (confidential endpoint) or the proxy just acquires a new stack for that user's and model/task, so that it then can handle such large volumes of concurrent requests at the same time.
Confidential endpoints requires a full retrial (no stack to be bought by the proxy), as the request was encrypted with a specific stack assigned …
=> feat: handle too early requests

atoma-proxy/src/server/handlers/nodes.rs
Fix the locked compute units. Prune every stack before locking. And lock the units in thread, so when we lock the lock is stored in memory.
=> fix: lock compute units

atoma-proxy/docs/openapi.yml, atoma-proxy/src/server/components/openapi.rs, atoma-proxy/src/server/config.rs, atoma-proxy/src/server/handlers/models.rs, atoma-proxy/src/server/http_server.rs, config.example.toml, docker-compose.yaml, open_router.example.json
Add new open router models endpoint.
It just copy the content of the json file. So we need to add proper file. The `open_router.json` is mapped to docker to provide the content.
=> feat: add OpenRouter models support and configuration

Cargo.lock, Cargo.toml, atoma-proxy-service/Cargo.toml, atoma-proxy-service/src/handlers/auth.rs, atoma-proxy-service/src/handlers/stats.rs
Bumps: 
- sui version to 1.46.2
- utoipa to 5.3.1
- utoipa-swagger-ui to 9.0.1
- axum to 0.8.3
=> chore: bump sui,utoipa,axum version

atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/grafana.rs, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/config.rs, atoma-proxy-service/src/handlers/stats.rs, atoma-proxy-service/src/proxy_service.rs, atoma-proxy/src/main.rs, config.example.toml
Add stats endpoint.
Stats will pull all dashboards that are tagged as "stats". Only `Stat` charts should be marked as this.
The name has to match the name in the dashboard UI. e.g. `Performance`
This way we can pull not just graphs but also stats from grafana/prometheus.
Also merge get_graphs into single endpoint. This way we run only queries that are defined in grafana.
=> feat: add stats (open router branch)

atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/metrics.rs
If a user intentionally cancells a stream, we should return the proper error message which indicates that it's a client error and not a fault of the service
=> chore: track cancelled streams

atoma-state/src/lib.rs, atoma-state/src/network.rs, atoma-state/src/state_manager.rs
We would like to see what the network bandwidth latency between the nodes and the proxy is to ensure that this is not negatively impacting service requests
=> feat: add metrics to track latency from proxy to node

atoma-proxy/src/server/handlers/chat_completions.rs
The `TOTAL_COMPLETED_REQUESTS` was added twice.
=> fix: total completed requests metrics

atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/streamer.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250507153627_drop_total_hash.sql, atoma-state/src/state_manager.rs, atoma-state/src/tests.rs, atoma-state/src/types.rs
This PR drops the unused `total_hash` field which is no longer needed since we are no longer relying on cross validation sampling consensus
=> fix: optimize total hash storage

docker-compose.yaml, prometheus.yml
This will help to give us observability over our disk usage and other OS metrics needed for alerts.
In this case I can monitor `node_filesystem_avail_bytes{mountpoint="/var/lib/docker"}`
where we could have alerts such as 
```
(
100 * (1 - node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) > 85
and
rate(node_disk_read_bytes_total[5m]) > 0
)
```
when our disk usage exceeds 85% for instance
=> feat: add node exporter for storage usage observability

atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-state/src/state_manager.rs
For image generations/embeddings we only locked but never actually marked it as used.
Calculate the num of request for fiat payments.
=> fix: fiat/stack updates

atoma-proxy/src/server/handlers/mod.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250528070551_usage-per-day.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add usage per day per user per model. The usage includes the input/output amount(USD)/tokens. I didn't wanted to include the total, because that's computable from the table, so we are saving space.
=> feat: add usage per day/user/model

atoma-proxy/src/server/handlers/chat_completions.rs
Instead of failing, send too many requests, becuase that's probably what it is.
=> feat: sends too many requests when we fails communicating with the node

atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/http_server.rs
Don't create client for each request, but pre-create it once for all requests.
=> feat: don't create client per request

Dockerfile
Add missing `libclang-dev` for newest sui.
=> fix: dockerfile changes for newest sui

atoma-proxy/src/server/handlers/completions.rs
Return http code 429 (too many request) when there is error in sending request to the node.
=> feat: return too many request on no response from the node

deny.toml
Fix cargo deny by adding ignore RUSTSEC into the deny.toml. Removed unusued ignored RUSTSEC
=> fix: cargo deny check

atoma-proxy/src/server/error.rs, atoma-proxy/src/server/middleware.rs
This pull request introduces a new error type to handle fiat payment restrictions and updates the middleware logic to enforce this restriction. The changes focus on improving error handling and simplifying the logic for unsupported payment methods.
* Added a new error variant `FiatPaymentsOnly` to the `AtomaProxyError` enum in `atoma-proxy/src/server/error.rs`. This error includes a message and endpoint details to provide more specific feedback when only fiat payments are supported.
* Removed the logic for retrieving stacks for a model in `atoma-proxy/src/server/middleware.rs` and replaced it with an error response using the newly added `FiatPaymentsOnly` error. This simplifies the code path for scenarios where fiat payments are enforced.
=> feat: forbid stacks
