.gitignore, Cargo.lock, Cargo.toml, atoma-proxy/Cargo.toml, atoma-proxy/src/main.rs, atoma-proxy/src/server/config.rs, atoma-proxy/src/server/mod.rs, atoma-state/src/lib.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs, config.example.toml
Add axum server with node subscription capabilities.
Fix the postgres queries.
=> feat: add axum server with node subscription

atoma-proxy/src/main.rs, atoma-proxy/src/sui/mod.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Filter stacks stored in the DB by the sui address.
=> feat: filter stacks by sui address

atoma-proxy/src/server/mod.rs, atoma-proxy/src/sui/mod.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
- add `/v1/models` endpoint
- fix some types
- add also selected stack to the request
=> fix: small fixes

Cargo.lock, Cargo.toml, atoma-proxy/Cargo.toml, atoma-proxy/src/main.rs, atoma-proxy/src/server/config.rs, atoma-proxy/src/server/mod.rs, atoma-proxy/src/sui/mod.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add tokenizers to the proxy for tokens estimation. Update the stacks with this.
During stack creation we have the event so we can update the DB right away.
=> feat: add tokenizers and estimate token use

atoma-state/src/state_manager.rs
Use full db url with the db name.
=> feat: use full db url with the db name

Cargo.lock, Cargo.toml, atoma-proxy/Cargo.toml, atoma-proxy/src/main.rs, atoma-proxy/src/server/http_server.rs
now there is global shutdown
- it's triggered when one of the task fails, or ctrl_c is pressed
- it will properly shutdown other tasks
=> fix: proper shutdown/failure

atoma-proxy/src/server/chat_completions.rs, atoma-proxy/src/server/streamer.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
forgot to push, should be part of the already LGTM #32
=> fix: split performance into prefill/decode

Cargo.lock, atoma-proxy/docs/openapi.yml, atoma-proxy/src/main.rs, atoma-state/src/handlers.rs
- Sync with changes on atoma-node.
- update the openai.yml
=> fix: missing atoma event

atoma-proxy/src/server/middleware.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20241213104339_create_initial_schema.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add `user_id` to `stacks` table.
The stacks that proxy creates are owned by individual users.
=> feat: add user_id to stacks

Cargo.lock, atoma-state/src/migrations/20241213104339_create_initial_schema.sql, atoma-state/src/state_manager.rs
=> fix: table name typos

Cargo.lock, atoma-auth/Cargo.toml, atoma-auth/src/auth.rs, atoma-auth/src/lib.rs, atoma-auth/src/sui/mod.rs, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-proxy/src/main.rs, atoma-proxy/src/server/http_server.rs, atoma-proxy/src/server/middleware.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20241230131705_add_balance_table.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add balance table (with usdc)
Add the ability to process usdc payments.
=> feat: add usdc balance for the user

atoma-auth/src/auth.rs, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-proxy-service/src/handlers/stacks.rs, atoma-proxy/docs/openapi.yml, atoma-state/src/handlers.rs, atoma-state/src/migrations/20241230125157_add_timestamp_to_stack.sql, atoma-state/src/state_manager.rs
Add endpoints to get stacks for the user, and the balance, both is for the dashboard billings page.
=> feat: get balance and stacks for user

atoma-proxy/src/main.rs
=> fix logs on atoma proxy

atoma-proxy/src/server/middleware.rs
Deduct correct amount from users balance.
=> fix: deduct correct amount of usdc

atoma-auth/src/sui/mod.rs, atoma-proxy-service/src/handlers/tasks.rs
=> fix: coin select

atoma-auth/src/sui/mod.rs
Merge USDC coins to cover the cost of the stack.
=> feat: merge usdc coins

atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add get user profile (currently only email, but I'm expecting we add username, bio, picture...) endpoint.
=> feat: get user profile endpoint

atoma-state/src/state_manager.rs
When the user was not present the query didn't fail, it just updated zero rows. Now we check if the row was affected.
=> fix: users without balance should fail when deducting

config.example.toml, docker-compose.yaml
=> fix: docker ports

atoma-state/src/migrations/20250124145133_timestamp.sql
Add timestamps to `users`/`api_tokens` tables. So we have some more informations.
=> feat: add timestamps to users/api_tokens tables

atoma-proxy/src/server/streamer.rs
=> feat: handle partial keep alive chunks

atoma-proxy/src/server/error.rs, atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/handlers/nodes.rs, atoma-proxy/src/server/middleware.rs
Change some errors to new error messages, introduce balance error.
=> refactor: better errors

atoma-proxy/src/server/error.rs, atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/handlers/mod.rs, atoma-proxy/src/server/handlers/nodes.rs, atoma-proxy/src/server/middleware.rs, atoma-proxy/src/server/mod.rs
Added optional client message to internal error.
Please double check the filled message, so we don't accidentaly sends something that we shouldn't
=> feat: add client message to internal error

atoma-state/src/errors.rs, atoma-state/src/handlers.rs, atoma-state/src/lib.rs, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Closes https://github.com/atoma-network/atoma-proxy/issues/233
=> refactor: add more granular errors

Cargo.lock, Cargo.toml
=> feat: bump up the sui version

atoma-proxy/src/telemetry.rs, otel-collector-config.yaml, prometheus.yml
Replicates the work done on https://github.com/atoma-network/atoma-node/pull/445 for correct p2p logging
=> build: add correct libp2p`loki` config

config.example.toml
Add metrics collection configuration to example config
=> feat: add metrics collection configuration to example config

atoma-auth/src/auth.rs, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-proxy/src/main.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250305142648_username-name.sql, atoma-state/src/state_manager.rs, atoma-state/src/tests.rs, atoma-state/src/types.rs
1) Change the `username` to `email` in the `users` table.
2) Add `name` to the `users` table
3) Add the endpoint for setting the profile
=> feat: add name to user, and endpoint for setting profile

Cargo.lock, config.example.toml, deny.toml, docker-compose.yaml
Integrating the work from https://github.com/atoma-network/atoma-node/pull/468
=> build: add bootstrap proxy config

.gitignore, atoma-proxy-service/docs/openapi.yml, atoma-state/src/state_manager.rs
=> feat: make email readonly

atoma-auth/src/auth.rs, atoma-proxy-service/docs/openapi.yml, atoma-proxy-service/src/components/openapi.rs, atoma-proxy-service/src/handlers/auth.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250318080012_add-password-salt.sql, atoma-state/src/state_manager.rs, atoma-state/src/tests.rs, atoma-state/src/types.rs
Add password salt for password hashing
Rename salt to zk_salt to distinguish these two salts
=> feat: add password salt for password hashing

atoma-proxy-service/src/components/grafana.rs, atoma-proxy-service/src/handlers/stats.rs
Add `unit` to resposne for graphs in grafana.
Also change the tuple to proper struct so it's easier to see what's what.
=> feat: add unit to grafana response

atoma-proxy-service/src/components/grafana.rs, atoma-proxy-service/src/handlers/stats.rs
Add graph type to be exported from grafana.
=> feat: add graph type export from grafana

atoma-auth/src/auth.rs
Retry the get_balance couple times to account for the sui sync.
=> feat: retry the get balance

atoma-auth/src/auth.rs
=> fix: build

.github/workflows/audit.yml
I'm ignoring these until https://github.com/MystenLabs/sui-rust-sdk/issues/107 is resolved
=> ci: ignore sui SDK related audits for now

atoma-proxy/src/server/handlers/nodes.rs, atoma-state/src/handlers.rs, atoma-state/src/state_manager.rs, atoma-state/src/tests.rs, atoma-state/src/types.rs
Fix the confidential stack selection.
=> fix: confidential stack select

atoma-proxy-service/docs/openapi.yml, atoma-proxy/src/server/middleware.rs
Acquire new stack in a thread so it's not affected by the connection drop.
=> feat: acquire new stack in thread

atoma-proxy/src/server/middleware.rs, atoma-state/src/state_manager.rs
Fix negative token when waiting for acquire new stack
=> fix: negative tokens

atoma-proxy/src/server/middleware.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250403075604_locked_compute_units-stacks.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Add locked compute units to stacks table.
=> feat: add locked compute units

atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/streamer.rs
=> fix streaming

config.example.toml
=> fix: config example

atoma-proxy/src/main.rs
Fail properly when tokenizers fail.
=> fix: fail properly

docker-compose.dev.yaml
A minor fix based on https://github.com/atoma-network/atoma-proxy/pull/387
=> build: update docker dev build

atoma-proxy/src/main.rs, atoma-proxy/src/server/config.rs, config.example.toml
Following up on the work done in https://github.com/atoma-network/atoma-node/pull/574
=> feat: heartbeat service

atoma-proxy-service/src/handlers/auth.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250424111320_fiat_payments.sql, atoma-state/src/state_manager.rs
=> feat: add tables for fiat

atoma-proxy/src/server/handlers/chat_completions.rs
=> fix: infinite stream kill

atoma-proxy/src/server/streamer.rs
Update stack hash on final chunk (same as on node)
=> feat: update stack hash

atoma-proxy/src/server/middleware.rs
Prioritize using fiat over owned stacks.
=> feat: use fiat when available

atoma-proxy-service/docs/openapi.yml, atoma-proxy/src/server/handlers/chat_completions.rs, atoma-proxy/src/server/handlers/completions.rs, atoma-proxy/src/server/handlers/embeddings.rs, atoma-proxy/src/server/handlers/image_generations.rs, atoma-proxy/src/server/handlers/mod.rs, atoma-proxy/src/server/handlers/request_model.rs, atoma-proxy/src/server/middleware.rs, atoma-proxy/src/server/streamer.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250515143255_split-computed-units.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
split tokens into input and output tokens
=> feat: split input output tokens

docker-compose.yaml
Set the retention policy to 1 year.
=> feat: add storage retention configuration for Prometheus

Cargo.lock, Cargo.toml, atoma-auth/Cargo.toml, atoma-auth/src/config.rs, atoma-proxy-service/Cargo.toml, atoma-proxy-service/src/config.rs, atoma-proxy/Cargo.toml, atoma-proxy/src/main.rs, atoma-proxy/src/server/config.rs, atoma-state/Cargo.toml, atoma-state/src/config.rs, atoma-state/src/config_error.rs, atoma-state/src/lib.rs, config.example.toml
I found that I was running into quite a few unexpected issues due to updated configurations that I may have overlooked, therefore adding more expressive config validation should eradicate these kinds of issues.
=> chore: add stronger config validation

atoma-proxy/src/server/streamer.rs
Remove chunks that have `"content": null`
=> fix: remove content null chunks

atoma-proxy/src/server/middleware.rs
If neither of `max_tokens` or `max_completion_tokens` is not filled, fill the `max_completion_tokens`.
=> feat: fill max completion tokens when not present
